var sql = require('mssql');
const poolConnection = require('../conection/poolConection');

exports.autoGenerateIns = async (req) => {
    try {
        //console.log("gg");
        const pool = await poolConnection.getPoolConnection(req); //crea coneccion.
        console.log("pollll");
        const result = await pool.request()
            .input('esquema',sql.VarChar(100),req.esquema)
            .execute('autogeneracion.gen_inserts'); //sql 
        sql.close();
        return result;
    } catch (err) {
        throw err;
    }
}

exports.autoGenerateDel= async (req) => {
    try {
        //console.log("gg");
        const pool = await poolConnection.getPoolConnection(req); //crea coneccion.
        console.log("pollll");
        const result = await pool.request()
            .input('esquema',sql.VarChar(100),req.esquema)
            .execute('autogeneracion.gen_delete'); //sql 
        sql.close();
        return result;
    } catch (err) {
        throw err;
    }
}

exports.autoGenerateRet = async (req) => {
    try {
        //console.log("gg");
        const pool = await poolConnection.getPoolConnection(req); //crea coneccion.
        console.log("pollll");
        const result = await pool.request()
            .input('esquema',sql.VarChar(100),req.esquema)
            .execute('autogeneracion.gen_retrieve'); //sql 
        sql.close();
        return result;
    } catch (err) {
        throw err;
    }
}

exports.autoGenerateUpd = async (req) => {
    try {
        //console.log("gg");
        const pool = await poolConnection.getPoolConnection(req); //crea coneccion.
        console.log("pollll");
        const result = await pool.request()
            .input('esquema',sql.VarChar(100),req.esquema)
            .execute('autogeneracion.gen_update'); //sql 
        sql.close();
        return result;
    } catch (err) {
        throw err;
    }
}