var express = require('express');
var router = express.Router();
var autogenerateQuery = require('../manager/autogenerateQuery');
var autogenerateQueryPG = require('../managerPG/autogenerateQueryPG');


router.post('/inserts', (req, res) => {
    try {
        console.log(req.body);

        if(req.body.tipo == 'mssql'){
        
            autogenerateQuery.autoGenerateIns(req.body).then(result=>{
                
                res.send(result.recordset); //cuando es un get en ".query" y .body espara las demas para el post ejemplo

            }).catch(err=>{
                res.send(err);
            });
        }
        else{
            autogenerateQueryPG.autoGenerateIns(req.body).then(result=>{
                
                res.send(result.recordset); //cuando es un get en ".query" y .body espara las demas para el post ejemplo

            }).catch(err=>{
                res.send(err);
            });
        }

    } catch (err) {
    
        res.send({ response:{data:err}, code: 406 });
    }
});

router.post('/delete', (req, res) => {
    try {
        console.log(req.body);

        if(req.body.tipo == 'mssql'){
        
            autogenerateQuery.autoGenerateDel(req.body).then(result=>{
                
                res.send(result.recordset); //cuando es un get en ".query" y .body espara las demas para el post ejemplo

            }).catch(err=>{
                res.send(err);
            });
        }
        else{
            autogenerateQueryPG.autoGenerateDel(req.body).then(result=>{
                
                res.send(result.recordset); //cuando es un get en ".query" y .body espara las demas para el post ejemplo

            }).catch(err=>{
                res.send(err);
            });
        }

    } catch (err) {
    
        res.send({ response:{data:err}, code: 406 });
    }
});

router.post('/retrieve', (req, res) => {
    try {
        console.log(req.body);

        if(req.body.tipo == 'mssql'){
        
            autogenerateQuery.autoGenerateRet(req.body).then(result=>{
                
                res.send(result.recordset); //cuando es un get en ".query" y .body espara las demas para el post ejemplo

            }).catch(err=>{
                res.send(err);
            });
        }
        else{
            autogenerateQueryPG.autoGenerateRet(req.body).then(result=>{
                
                res.send(result.recordset); //cuando es un get en ".query" y .body espara las demas para el post ejemplo

            }).catch(err=>{
                res.send(err);
            });
        }

    } catch (err) {
    
        res.send({ response:{data:err}, code: 406 });
    }
});

module.exports = router;